#!/usr/bin/env python3
"""Prepare deterministic EEPROM fixtures for save-recovery certification runs.

The files created here are prelaunch inputs for Ares save-recovery captures.
They are not logs, not evidence by themselves, and not release certification.
"""

from __future__ import annotations

import argparse
import json
import os
import stat
import struct
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools import n64game_certification as certification  # noqa: E402


SCHEMA = "n64game-certification-save-fixtures-v1"
SCENARIOS = ("valid_resume", "latest_corrupt_fallback", "all_corrupt_new_game")


class SaveFixtureError(ValueError):
    """The fixture directory or generated bytes are unsafe."""


def _require_output_directory(path: Path) -> None:
    if path.parent.exists() and path.parent.is_symlink():
        raise SaveFixtureError("output directory parent may not be a symlink")
    if path.exists():
        if path.is_symlink() or not path.is_dir():
            raise SaveFixtureError(f"output directory must be a non-symlink directory: {path}")
    else:
        path.mkdir(parents=True)


def _require_writable_regular_target(path: Path, label: str) -> None:
    if path.exists():
        info = path.lstat()
        if stat.S_ISLNK(info.st_mode) or not stat.S_ISREG(info.st_mode):
            raise SaveFixtureError(f"{label} must be a non-symlink regular file: {path}")


def _repo_relative(path: Path) -> str:
    try:
        return path.resolve(strict=False).relative_to(ROOT).as_posix()
    except ValueError:
        return os.fspath(path)


def save_slot(sequence: int, *, corrupt: bool = False, scene: int = 3, quest: int = 4) -> bytes:
    if sequence <= 0 or sequence > 0xFFFF_FFFF:
        raise SaveFixtureError("save sequence is outside the supported u32 range")
    if scene < 0 or scene > 5 or quest < 0 or quest > 7:
        raise SaveFixtureError("checkpoint scene/quest is outside the certification range")
    slot = bytearray(certification.SAVE_SLOT_BYTES)
    slot[:4] = b"N64G"
    struct.pack_into(">H", slot, 4, certification.SAVE_VERSION)
    struct.pack_into(">H", slot, 6, certification.SAVE_SLOT_BYTES)
    struct.pack_into(">I", slot, 8, sequence)
    slot[12] = 4
    slot[13:17] = b"TEST"
    slot[21] = scene
    slot[22] = quest
    slot[23] = 0x23
    struct.pack_into(">H", slot, 24, 92)
    struct.pack_into(">H", slot, 26, 78)
    struct.pack_into(">I", slot, 32, 100)
    struct.pack_into(">I", slot, 36, 50)
    slot[40] = 0
    slot[41] = 1
    checksum = certification._fnv1a(slot[:60])
    struct.pack_into(">I", slot, 60, checksum ^ (1 if corrupt else 0))
    return bytes(slot)


def eeprom_image(scenario: str) -> bytes:
    erased = bytes([0xFF]) * certification.SAVE_SLOT_BYTES
    if scenario == "valid_resume":
        payload = save_slot(5) + erased
    elif scenario == "latest_corrupt_fallback":
        payload = save_slot(5) + save_slot(6, corrupt=True)
    elif scenario == "all_corrupt_new_game":
        payload = save_slot(7, corrupt=True) + erased
    else:
        raise SaveFixtureError(f"unsupported save fixture scenario: {scenario}")
    return payload + bytes([0xFF]) * (certification.EEPROM_BYTES - len(payload))


def _slot_summary(image: bytes) -> dict[str, Any]:
    slots = [
        certification._save_slot(image[index * certification.SAVE_SLOT_BYTES:(index + 1) * certification.SAVE_SLOT_BYTES])
        for index in range(certification.SAVE_SLOT_COUNT)
    ]
    selected = certification._selected_slot(slots)
    return {
        "valid_slot_mask": sum((1 << index) for index, slot in enumerate(slots) if slot["valid"]),
        "selected_slot": selected,
        "slots": [
            {
                "index": index,
                "recognizable": bool(slot["recognizable"]),
                "checksum_ok": bool(slot["checksum_ok"]),
                "valid": bool(slot["valid"]),
                "sequence": int(slot["sequence"]),
                "scene": int(slot["scene"]),
                "quest": int(slot["quest"]),
            }
            for index, slot in enumerate(slots)
        ],
    }


def prepare(out_dir: Path) -> dict[str, Any]:
    out = Path(os.path.abspath(os.fspath(out_dir)))
    _require_output_directory(out)
    rows = []
    for scenario in SCENARIOS:
        image = eeprom_image(scenario)
        if len(image) != certification.EEPROM_BYTES:
            raise SaveFixtureError(f"{scenario} EEPROM image is not exactly 512 bytes")
        path = out / f"{scenario}.eep"
        _require_writable_regular_target(path, scenario)
        path.write_bytes(image)
        rows.append({
            "scenario": scenario,
            "path": _repo_relative(path),
            "sha256": certification._sha256(path),
            "bytes": len(image),
            **_slot_summary(image),
        })
    manifest = {
        "schema": SCHEMA,
        "certification": "NOT_CLAIMED",
        "status": certification.STATUS,
        "fixtures": rows,
        "limitations": [
            "These are deterministic prelaunch EEPROM inputs for Ares recovery captures.",
            "They are not raw logs, not evidence by themselves, and not release certification.",
            "Ares must still be launched with the matching --expected-eeprom-sha256 and the resulting log must pass the strict validator.",
        ],
    }
    manifest_path = out / "SAVE_FIXTURES.json"
    _require_writable_regular_target(manifest_path, "fixture manifest")
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", required=True, type=Path)
    arguments = parser.parse_args(argv)
    try:
        manifest = prepare(arguments.out_dir)
    except (OSError, ValueError) as exc:
        print(f"CERTIFICATION_SAVE_FIXTURES_FAIL: {exc}", file=sys.stderr)
        return 1
    print(json.dumps({
        "result": "CERTIFICATION_SAVE_FIXTURES_READY",
        "certification": "NOT_CLAIMED",
        "fixtures": [
            {
                "scenario": row["scenario"],
                "path": row["path"],
                "sha256": row["sha256"],
            }
            for row in manifest["fixtures"]
        ],
    }, sort_keys=True, separators=(",", ":")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
